stages:
  stage_01:
    cmd: python stage1.py
    deps:
    - stage1.py
    outs:
    - artifacts01.txt
  stage_02:
    cmd: python stage02.py
    deps:
    - artifacts01.txt  
    - stage02.py
  stage_03:
    cmd: python stage03.py
    deps:
    - artifacts01.txt  
    - stage03.py 
    outs:
    -  artifacts02.txt  
      